### ISSUE TITLE
Entries clean-up speed and settings

### ISSUE THREAD

**Issue by Misk-PST** [Commit-La-Grenouille/streamdeck-clipboard-buddy#3]
I've started using this on my Stream Deck for productivity. I consistently copy multiple different segments of text and paste them in different fields. This tool is very helpful, however, the 3 second hold time to delete is a bit cumbersome when deleting them all for the next project.  Is it possible to have the toggle-able option to instead delete with a 1-3 second hold and secure with a 3+ second hold?

**Comment by Commit-La-Grenouille** [comment]
Hi @Misk-PST,
I am glad that the plugin is useful to you too :)

You scenario is giving me some ideas (new and old) and I will try what I can come up with despite my limited Objective-C skills 😛 

Stay tuned for the next update ;)

**Comment by Commit-La-Grenouille** [comment]
Hi @Misk-PST,

I managed to make a quick release with a new action that clear all the entries in one go (way faster than the one-by-one):
https://github.com/Commit-La-Grenouille/streamdeck-clipboard-buddy/releases/tag/0.6.0

I will try to look into creating a settings view to allow users to tune the press duration but it will take more time.

**Comment by Commit-La-Grenouille** [comment]
Hi @Misk-PST,

the new 0.7.0 release should be even more useful to you with some simpler storage solution (making the clearing faster too) and a row-purge action in case the global cleaner was a bit too much ;)
